const API_URL="https://script.google.com/macros/s/AKfycbzuEEeAptN9MenKWY1oynX6c3gmGY7HgVXyGiGWGaoXeNOrmNNMUBCtXnutHVxJ13rv/exec";
const APP_VERSION="1.9.0";
const FIXED_PREFIX=/^50-(200[1-9]|201[0-9]|202[0-1])$/;
const EXTERNAL_PREFIX=/^\d{1,20}$/;
const NAME_PATTERN=/^[A-Za-zÀ-ÖØ-öø-ÿ ]{2,80}$/;
const DESC_PATTERN=/^[A-Za-zÀ-ÖØ-öø-ÿ0-9 .,:;()\/-]{3,300}$/;
const STEPS=["Identificação","Parte externa","Parte interna","Motor","Fotos finais","Resumo e envio"];
const ITEMS={
 external:[
  {key:"lataria_geral",name:"Lataria Geral",aliases:["lataria","capo","porta","para_choque","para_lama","lateral","teto","grade"]},
  {key:"vidros_para_brisas",name:"Vidros e Para-brisas",aliases:["vidro","para_brisa","retrovisor","limpador"]},
  {key:"iluminacao_externa",name:"Iluminação Externa",note:"Faróis, lanternas e giroflex",aliases:["farol","lanterna","luz","giroflex","iluminacao"]}
 ],
 internal:[
  {key:"multimidia",name:"Multimídia",aliases:["multimidia","radio","tablet","modulo"]},
  {key:"ar_condicionado",name:"Ar-condicionado",aliases:["ar_condicionado","ventilacao"]},
  {key:"painel_instrumentos",name:"Painel de Instrumentos",aliases:["painel"]},
  {key:"freio",name:"Freio",note:"Inclui freio de estacionamento",aliases:["freio"]},
  {key:"buzina",name:"Buzina",aliases:["buzina"]},
  {key:"sirene",name:"Sirene",aliases:["sirene","alto_falante","megafone"]},
  {key:"xadrez",name:"Xadrez",aliases:["xadrez","detidos"]},
  {key:"tapete",name:"Tapete",aliases:["tapete"]},
  {key:"estepe",name:"Estepe",note:"Obrigatório",aliases:["estepe"]},
  {key:"macaco",name:"Macaco",optional:true,aliases:["macaco"]},
  {key:"triangulo",name:"Triângulo",optional:true,aliases:["triangulo"]},
  {key:"chave_roda",name:"Chave de roda",optional:true,aliases:["chave_de_roda","chave_roda"]}
 ],
 engine:[{key:"motor_geral",name:"Verificação geral do motor",aliases:["motor","oleo","vazamento","bateria","correia","mangueira"]}]
};
const FINAL_PHOTOS=[{type:"frontal",label:"Frente"},{type:"traseira",label:"Traseira"},{type:"lado_esquerdo",label:"Lado esquerdo"},{type:"lado_direito",label:"Lado direito"}];
const state={step:1,status:{},descriptions:{},photos:{},pending:[],decisions:{},device:{}};
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
window.addEventListener("DOMContentLoaded",()=>{buildPrefixes();buildStepper();renderItems();renderFinalPhotos();bind();detectDevice();registerSW();showStep(1)});
function buildPrefixes(){let html='<option value="">Selecione</option>';for(let n=2001;n<=2021;n++)html+=`<option value="50-${n}">50-${n}</option>`;html+='<option value="OUTRO">Outro prefixo</option>';$("#prefixoSelect").innerHTML=html}
function buildStepper(){$("#stepDots").innerHTML=STEPS.map((_,i)=>`<button type="button" class="step-dot" data-jump="${i+1}">${i+1}</button>`).join("")}
function renderItems(){renderGroup("externalItems",ITEMS.external);renderGroup("internalItems",ITEMS.internal);renderGroup("engineItems",ITEMS.engine)}
function renderGroup(id,items){$("#"+id).innerHTML=items.map(item=>`<article class="inspection-card" data-key="${item.key}"><h3>${escapeHtml(item.name)}</h3><p class="item-note">${escapeHtml(item.note|| (item.optional?"Opcional — use Não se aplica quando ausente de fábrica.":"Selecione a condição encontrada."))}</p><div class="known-damages"></div><div class="status-buttons"><button type="button" class="status-choice ok" data-status="ok">SEM ALTERAÇÃO</button><button type="button" class="status-choice change" data-status="nao">COM ALTERAÇÃO</button>${item.optional?'<button type="button" class="status-choice na" data-status="na">NÃO SE APLICA</button>':''}</div><div class="change-panel" hidden><textarea maxlength="300" placeholder="Descreva a alteração encontrada"></textarea><div class="inline-photo"><button type="button" data-capture="avaria_${item.key}">INSERIR FOTO DA ALTERAÇÃO</button><input id="photo_avaria_${item.key}" type="file" accept="image/*" capture="environment" hidden><div class="photo-preview"></div></div></div></article>`).join("")}
function renderFinalPhotos(){$("#finalPhotoGrid").innerHTML=FINAL_PHOTOS.map(p=>`<div class="photo-card" data-photo-card="${p.type}"><h3>${p.label}</h3><p>Obrigatória</p><button type="button" data-capture="${p.type}">INSERIR FOTO</button><input id="photo_${p.type}" type="file" accept="image/*" capture="environment" hidden><div class="photo-preview"></div></div>`).join("")}
function bind(){document.addEventListener("click",e=>{const n=e.target.closest(".next-button"),p=e.target.closest(".prev-button"),c=e.target.closest(".status-choice"),cap=e.target.closest("[data-capture]"),rm=e.target.closest(".remove-photo"),dd=e.target.closest("[data-damage-decision]");if(n)next(Number(n.dataset.next));if(p)showStep(Number(p.dataset.prev));if(c)setStatus(c.closest(".inspection-card"),c.dataset.status);if(cap)$("#photo_"+cap.dataset.capture).click();if(rm){delete state.photos[rm.dataset.removePhoto];renderPhoto(rm.dataset.removePhoto)}if(dd){state.decisions[dd.dataset.damageId]=dd.dataset.damageDecision;renderKnownDamages()}});document.addEventListener("change",async e=>{if(e.target.id==="prefixoSelect"){const other=e.target.value==="OUTRO";$("#otherPrefixWrap").hidden=!other;if(!other)$("#otherPrefix").value="";await loadPending()}if(e.target.type==="file"&&e.target.id.startsWith("photo_")){const type=e.target.id.replace("photo_","");if(e.target.files[0])await loadPhoto(type,e.target.files[0])}});document.addEventListener("input",e=>{if(e.target.id==="condutor")e.target.value=e.target.value.replace(/[^A-Za-zÀ-ÖØ-öø-ÿ ]/g,"").replace(/\s+/g," ");if(["rg","kmInicial","otherPrefix"].includes(e.target.id))e.target.value=e.target.value.replace(/\D/g,"");if(e.target.matches(".change-panel textarea")){const key=e.target.closest(".inspection-card").dataset.key;e.target.value=sanitizeDescription(e.target.value);state.descriptions[key]=e.target.value.trim()}});$("#checklistForm").addEventListener("submit",submit);$("#newChecklistButton").onclick=()=>location.reload();$("#closeAndRefreshButton").onclick=()=>location.reload()}
function getPrefix(){return $("#prefixoSelect").value==="OUTRO"?$("#otherPrefix").value.trim():$("#prefixoSelect").value}
async function loadPending(){state.pending=[];state.decisions={};const prefix=getPrefix();$("#pendingSummary").hidden=true;if(!prefix||(!FIXED_PREFIX.test(prefix)&&!EXTERNAL_PREFIX.test(prefix)))return;try{const r=await fetch(`${API_URL}?action=avariasPendentes&prefixo=${encodeURIComponent(prefix)}`,{cache:"no-store"});const data=await r.json();if(!data.success)throw new Error(data.message||"Falha na consulta");state.pending=data.avarias||[];renderPendingSummary();renderKnownDamages()}catch(err){toast("Não foi possível consultar avarias: "+err.message)}}
function renderPendingSummary(){const box=$("#pendingSummary");if(!state.pending.length){box.innerHTML="<h3>Nenhuma avaria pendente</h3><p>Não há registros administrativos em aberto para esta viatura.</p>";box.hidden=false;return}box.innerHTML=`<h3>${state.pending.length} avaria(s) pendente(s)</h3>${state.pending.map(d=>`<p><strong>${escapeHtml(d.item||"Item não informado")}</strong> — ${escapeHtml(d.descricao||"")} (${escapeHtml(d.situacao||"PENDENTE")})</p>`).join("")}`;box.hidden=false}
function matchDamageToKey(d){const text=normalizeKey(`${d.item||""} ${d.posicaoLocal||""}`);for(const group of Object.values(ITEMS))for(const item of group)if(item.aliases.some(a=>text.includes(a)))return item.key;return ""}
function renderKnownDamages(){$$(".inspection-card").forEach(card=>{const host=card.querySelector(".known-damages"),key=card.dataset.key;const damages=state.pending.filter(d=>matchDamageToKey(d)===key);host.innerHTML=damages.map(d=>`<div class="damage-alert"><strong>AVARIA JÁ REGISTRADA</strong><div class="damage-meta">Data: ${escapeHtml(d.dataDeteccao||"não informada")} · Condutor: ${escapeHtml(d.registradoPor||"não informado")} · Local: ${escapeHtml(d.posicaoLocal||d.item||"não informado")} · Situação: ${escapeHtml(d.situacao||"PENDENTE")}</div><p class="damage-desc">${escapeHtml(d.descricao||"Sem descrição.")}</p><div class="damage-actions"><button type="button" data-damage-id="${escapeHtml(d.idAvaria)}" data-damage-decision="continua" class="${state.decisions[d.idAvaria]==="continua"?"selected":""}">CONTINUA IGUAL</button><button type="button" data-damage-id="${escapeHtml(d.idAvaria)}" data-damage-decision="agravou" class="${state.decisions[d.idAvaria]==="agravou"?"selected":""}">AGRAVOU</button><button type="button" data-damage-id="${escapeHtml(d.idAvaria)}" data-damage-decision="solicitar_verificacao" class="${state.decisions[d.idAvaria]==="solicitar_verificacao"?"selected":""}">SOLICITAR VERIFICAÇÃO</button></div></div>`).join("")})}
function setStatus(card,status){const key=card.dataset.key;state.status[key]=status;card.classList.toggle("is-ok",status==="ok"||status==="na");card.classList.toggle("is-change",status==="nao");card.querySelectorAll(".status-choice").forEach(b=>b.classList.toggle("selected",b.dataset.status===status));card.querySelector(".change-panel").hidden=status!=="nao";if(status!=="nao"){delete state.descriptions[key];delete state.photos["avaria_"+key];const ta=card.querySelector("textarea");if(ta)ta.value="";renderPhoto("avaria_"+key)}}
async function loadPhoto(type,file){if(!file.type.startsWith("image/")){toast("Selecione uma imagem válida.");return}try{state.photos[type]=await compressImage(file);renderPhoto(type)}catch(err){toast("Falha ao processar a foto.")}}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement("canvas");canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext("2d").drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const dataUrl=canvas.toDataURL("image/jpeg",.72);resolve({tipo:"",name:(file.name||"foto.jpg").replace(/[^A-Za-z0-9._-]/g,"_"),mimeType:"image/jpeg",data:dataUrl.split(",")[1]})};img.onerror=reject;img.src=url})}
function renderPhoto(type){const input=$("#photo_"+CSS.escape(type));if(!input)return;const host=input.parentElement.querySelector(".photo-preview"),photo=state.photos[type];host.innerHTML=photo?`<img src="data:${photo.mimeType};base64,${photo.data}" alt="Prévia"><button type="button" class="remove-photo" data-remove-photo="${type}">REMOVER</button>`:""}
function next(target){if(!validateStep(state.step))return;if(target===6)renderSummary();showStep(target)}
function validateStep(step){hideErrors();if(step===1){const prefix=getPrefix(),name=$("#condutor").value.trim(),rg=$("#rg").value.trim(),km=$("#kmInicial").value.trim(),fuel=$("#combustivel").value;let msg="";if(!prefix||(!FIXED_PREFIX.test(prefix)&&!EXTERNAL_PREFIX.test(prefix)))msg="Selecione uma viatura ou informe um prefixo externo somente numérico.";else if(!NAME_PATTERN.test(name))msg="O nome de guerra deve conter somente letras e espaços.";else if(!/^\d{1,20}$/.test(rg))msg="O RG deve conter somente números.";else if(!/^\d{1,9}$/.test(km))msg="O KM deve conter somente números.";else if(!fuel)msg="Selecione o nível de combustível.";else if(!state.photos.odometro||!state.photos.combustivel)msg="Insira as fotos do odômetro e do marcador de combustível.";if(msg)return error("identificationError",msg),false;return true}if(step>=2&&step<=4){const items=step===2?ITEMS.external:step===3?ITEMS.internal:ITEMS.engine;for(const item of items){const st=state.status[item.key];if(!st)return sectionError(step,`Avalie o item: ${item.name}`),false;if(st==="nao"){if(!DESC_PATTERN.test(state.descriptions[item.key]||""))return sectionError(step,`Descreva corretamente a alteração em: ${item.name}`),false;if(!state.photos["avaria_"+item.key])return sectionError(step,`Insira a foto da alteração em: ${item.name}`),false}}const related=state.pending.filter(d=>items.some(i=>i.key===matchDamageToKey(d)));for(const d of related)if(!state.decisions[d.idAvaria])return sectionError(step,"Informe a situação das avarias já registradas exibidas nesta etapa."),false;return true}if(step===5){for(const p of FINAL_PHOTOS)if(!state.photos[p.type])return error("finalPhotosError",`Insira a foto obrigatória: ${p.label}.`),false;return true}return true}
function sectionError(step,msg){const page=$(`[data-page="${step}"]`),el=page.querySelector(".section-error");el.textContent=msg;el.hidden=false;toast(msg)}
function hideErrors(){$$(".form-error").forEach(e=>e.hidden=true)}function error(id,msg){const el=$("#"+id);el.textContent=msg;el.hidden=false;toast(msg)}
function showStep(step){state.step=step;$$('.form-page').forEach(p=>p.hidden=Number(p.dataset.page)!==step);$$('.step-dot').forEach((d,i)=>{d.classList.toggle('active',i+1===step);d.classList.toggle('done',i+1<step)});$("#progressBar").style.width=((step-1)/(STEPS.length-1)*100)+"%";$("#stepLabel").textContent=`Etapa ${step} de ${STEPS.length} — ${STEPS[step-1]}`;scrollTo({top:0,behavior:"smooth"})}
function renderSummary(){const changed=Object.keys(state.status).filter(k=>state.status[k]==="nao");$("#summaryContent").innerHTML=`<div class="summary-block"><h3>Identificação</h3><p><strong>Viatura:</strong> ${escapeHtml(getPrefix())}</p><p><strong>Nome de guerra:</strong> ${escapeHtml($("#condutor").value)}</p><p><strong>RG:</strong> ${escapeHtml($("#rg").value)}</p><p><strong>KM:</strong> ${escapeHtml($("#kmInicial").value)}</p><p><strong>Combustível:</strong> ${escapeHtml($("#combustivel").value)}</p></div><div class="summary-block"><h3>Resultado</h3><p><strong>Itens avaliados:</strong> ${Object.keys(state.status).length}</p><p><strong>Com alteração:</strong> ${changed.length}</p>${changed.map(k=>`<p><strong>${escapeHtml(itemName(k))}:</strong> ${escapeHtml(state.descriptions[k])}</p>`).join("")||"<p>Sem novas alterações.</p>"}</div><div class="summary-block"><h3>Avarias pendentes conhecidas</h3><p>${state.pending.length} registro(s) permanecem sob controle administrativo.</p></div>`}
async function submit(e){e.preventDefault();if(!validateStep(5)||!validateStep(4)||!validateStep(3)||!validateStep(2)||!validateStep(1)){toast("Revise as etapas anteriores.");return}if(!$("#finalConfirmation").checked){error("submitError","Confirme a declaração final antes de enviar.");return}const photos=Object.entries(state.photos).map(([type,p])=>({...p,tipo:type}));const known=state.pending.map(d=>({idAvaria:d.idAvaria,item:d.item,itemKey:matchDamageToKey(d)||normalizeKey(d.item),decisao:state.decisions[d.idAvaria]})).filter(d=>d.decisao);const payload={action:"salvarRetiradaMobile",data:{tipoChecklist:"CONDUTOR",prefixo:getPrefix(),dataCliente:new Date().toISOString().slice(0,10),condutor:$("#condutor").value.trim(),rg:$("#rg").value.trim(),kmInicial:$("#kmInicial").value.trim(),combustivel:$("#combustivel").value,itens:state.status,descricoesAlteracoes:state.descriptions,avariasConhecidas:known,fotos:photos,dispositivo:state.device,versaoFrontend:APP_VERSION}};$("#sendingModal").hidden=false;try{const res=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});const data=await res.json();if(!data.success)throw new Error(data.message||"Não foi possível registrar.");$("#sendingModal").hidden=true;$("#successMessage").textContent=`Protocolo: ${data.protocolo} · Status: ${data.status}`;$("#successModal").hidden=false}catch(err){$("#sendingModal").hidden=true;error("submitError",err.message||"Falha no envio.");showStep(6)}}
function itemName(key){for(const g of Object.values(ITEMS)){const i=g.find(x=>x.key===key);if(i)return i.name}return key.replace(/_/g," ")}
function sanitizeDescription(v){return v.replace(/[^A-Za-zÀ-ÖØ-öø-ÿ0-9 .,:;()\/-]/g,"").replace(/\s+/g," ").slice(0,300)}
function normalizeKey(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")}
function escapeHtml(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function toast(msg){const t=$("#toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._id);t._id=setTimeout(()=>t.classList.remove("show"),3200)}
function detectDevice(){state.device={tipo:/Mobi|Android/i.test(navigator.userAgent)?"MOBILE":"DESKTOP",navegador:navigator.userAgent.slice(0,100),idioma:navigator.language,resolucao:`${screen.width}x${screen.height}`}}
function registerSW(){if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js?v=1.9.0").catch(()=>{})}
